name: PR-pipeline_hccl

concurrency:
  max: 10
  exceed-action: QUEUE
  enable: true
  preemption:
    enable: true
    events: [mr_id]

on:
  pr_comment:
      types: [ created ]
      keyword: '^(?:\/)?compile*'
  pull_request_comment:
    types: [created]
    branches: [ '**' ]
    comments: [ '^(?:\/)?compile*' ]

env:
  org_name: ${{ vars.ORG_NAME }}
  repo_name: ${{ atomgit.event.repository.name }}
  MERGE_ID: ${{ atomgit.event.pull_request.number }}
  TARGET_BRANCH: ${{atomgit.base_ref}}
  SOURCE_BRANCH: ${{atomgit.head_ref}}
  obs_path: "${{ env.org_name }}/${{ env.repo_name }}/ci/package/${{ env.MERGE_ID }}"   
  obs_smoke_path_A2: "${{ env.obs_path }}/presmoke/2" 
  obs_smoke_path_A3: "${{ env.obs_path }}/presmoke/3"
  online: ${{ vars.APPLY_LABEL }}

stages:
  stage1:
    name: PreBuild
    jobs:
      JOB_image:
        name: Test_image
        steps:
          - name: revise_image
            identifier: revise_image
            uses: cann/.gitcode/actions/revise-img@master
            with:
              repo_name: ${{ env.repo_name }}
              target_branch: ${{ env.TARGET_BRANCH }}
              comment: ${{ atomgit.event.comment.body }}
              token: ${{secrets.GIT_TOKEN}}
        runs-on: ['self-hosted', 'arch=x64', 'spec=slim']
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/ubuntu20.04.05_x86:k8s_v1.1006
      JOB_pre:
        name: Test_PreBuild
        uses: cann/.gitcode/.gitcode/workflows/pre_action.yml@master
    pre:
    - type: auto
    fail-fast: true
  stage2:
    name: Compile
    jobs:
      JOB_codecheck:
        name: CodeCheck
        uses: cann/.gitcode/.gitcode/workflows/codecheck_action.yml@master
        with:
          precommit_image_version: ${{ jobs.JOB_image.outputs.precommit }}
          codecheck_image_version: ${{ jobs.JOB_image.outputs.codecheck }}
      JOB_x86_compile:
        name: Compile_Ascend_X86
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_X86'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_X86 }}
          arch: 'x64'
          package_name: 'cann-hccl_linux-x86_64.run'
      JOB_x86_compile_ubuntu24:
        name: Compile_Ascend_X86_ubuntu24
        uses: .gitcode/workflows/compile_action.yml
        with: 
          task_name: 'Compile_Ascend_X86_ubuntu24'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_X86_ubuntu24 }}
          arch: 'x64'
          package_name: 'cann-hccl_linux-x86_64_ubuntu24.run'
      JOB_x86_compile_monitor:
        name: Compile_Ascend_X86_monitor
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_X86_monitor'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_X86_monitor }}
          arch: 'x64'
          package_name: 'cann-hccl_linux-x86_64_monitor.run'
        if: env.TARGET_BRANCH == 'master'
      JOB_arm_compile:
        name: Compile_Ascend_ARM
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_ARM'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_ARM }}
          arch: 'arm64'
          package_name: 'cann-hccl_linux-aarch64.run'
      JOB_arm_compile_ubuntu24:
        name: Compile_Ascend_ARM_ubuntu24
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_ARM_ubuntu24'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_ARM_ubuntu24 }}
          arch: 'arm64'
          package_name: 'cann-hccl_linux-aarch64_ubuntu24.run'
      JOB_arm_compile_monitor:
        name: Compile_Ascend_ARM_monitor
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_ARM_monitor'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_ARM_monitor }}
          arch: 'arm64'
          package_name: 'cann-hccl_linux-aarch64_monitor.run'
        if: env.TARGET_BRANCH == 'master'
      JOB_staticcheck_md_check:
        name: CodeCheck_staticcheck_md_check
        uses: .gitcode/workflows/staticcheck_action.yml
        with:
          check_type: 'md_check'
          image_version: ${{ jobs.JOB_image.outputs.staticcheck }}
    pre:
    - type: auto
    fail-fast: false
  stage3: 
    name: UT
    select: selected_by_default
    jobs:
      JOB_api_check:
        name: API_Check
        select: selected_by_default
        needs: []
        steps:
          - 
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
          -
            name: api_check
            identifier: api_check
            uses: cann/.gitcode/actions/api-check@master
            with:
              org_name: ${{ env.org_name }}
              mode: "check"
              repo_name: ${{ env.repo_name }}
              source_branch: ${{ env.SOURCE_BRANCH }}
              target_branch: ${{ env.TARGET_BRANCH }}
              merge_id: ${{ env.MERGE_ID }}
              WORKSPACE: ${{ steps.process_checkout.outputs.path }}
        if: "${{ default() }}"
        runs-on: ['self-hosted', 'arch=x64', 'spec=large']
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/${{ jobs.JOB_image.outputs.API_Check }}
      JOB_UT_TEST:
        name: UT_TEST
        select: selected_by_default
        needs: []
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'ut'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.UT_Test }}
      JOB_ST_TEST:
        name: ST_TEST
        select: selected_by_default
        needs: []
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'st'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.ST_Test }}
    pre:
    - type: auto
    fail-fast: false
  stage4:
    name: PreSmoke
    jobs:
      A2_smoke:
        name: PreSmoke_A2
        timeout-minutes: 30
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
          -
            name: download
            uses: obs-download
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{ secrets.AK }}
              secret-key: ${{ secrets.SK }}
              key: |
                ${{ env.obs_path }}/pr_filelist.txt
                ${{ env.obs_path }}/pr_filelist_mod.txt
                ${{ env.obs_path }}/update_file_detail.txt
                ${{ env.obs_path }}/pre_smoke.sh
              path: ${{ steps.process_checkout.outputs.path }}
          -
            name: smoke executor
            run: |
              export arm_run_url=${{jobs.JOB_arm_compile_ubuntu24.outputs.arm_run_url}}
              export obs_smoke_path=${{env.obs_smoke_path_A2}}
              export obs_path=${{ env.obs_path }}
              export repo_name=${{env.repo_name}}
              export pr_id=${{ env.MERGE_ID }}
              export AK=${{secrets.AK}}
              export SK=${{secrets.SK}}
              export WORKSPACE=${{ steps.process_checkout.outputs.path }}
              bash ${{ steps.process_checkout.outputs.path }}/pre_smoke.sh
          - name: upload
            uses: obs-upload
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{ secrets.AK }}
              secret-key: ${{ secrets.SK }}
              artifact-path: "${{ steps.process_checkout.outputs.path }}/slog*.tar.gz"
              object-prefix: ${obs_smoke_path}/plog/
        if: env.TARGET_BRANCH == 'master'
        runs-on: ['self-hosted','npu=2','smoke=204']
        container:
          image: swr.cn-south-1.myhuaweicloud.com/pre_smoke/${{ jobs.JOB_image.outputs.PreSmoke_A900_npupool }}
      A3_smoke:
        name: PreSmoke_A3
        timeout-minutes: 30
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
          -
            name: download
            uses: obs-download
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{ secrets.AK }}
              secret-key: ${{ secrets.SK }}
              key: |
                ${{ env.obs_path }}/pr_filelist.txt
                ${{ env.obs_path }}/pr_filelist_mod.txt
                ${{ env.obs_path }}/update_file_detail.txt
                ${{ env.obs_path }}/pre_smoke.sh
              path: ${{ steps.process_checkout.outputs.path }}
          -
            name: smoke executor
            run: |
              export arm_run_url=${{jobs.JOB_arm_compile_ubuntu24.outputs.arm_run_url}}
              export obs_smoke_path=${{env.obs_smoke_path_A3}}
              export obs_path=${{ env.obs_path }}
              export repo_name=${{env.repo_name}}
              export pr_id=${{ env.MERGE_ID }}
              export AK=${{secrets.AK}}
              export SK=${{secrets.SK}}
              export WORKSPACE=${{ steps.process_checkout.outputs.path }}
              bash ${{ steps.process_checkout.outputs.path }}/pre_smoke.sh
          - name: upload
            uses: obs-upload
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{ secrets.AK }}
              secret-key: ${{ secrets.SK }}
              artifact-path: "${{ steps.process_checkout.outputs.path }}/slog*.tar.gz"
              object-prefix: ${obs_smoke_path}/plog/
        if: env.TARGET_BRANCH == 'master'
        runs-on: ['self-hosted','npu=2','smoke=301']
        container:
          image: swr.cn-north-12.myhuaweicloud.com/pre_smoke/${{ jobs.JOB_image.outputs.PreSmoke_A3_npupool }}
    pre:
    - type: auto
    fail-fast: true

post:
  jobs:
    job_post:
      name: Test_post
      uses: cann/.gitcode/.gitcode/workflows/post_action.yml@master