name: PR-pipeline_hcomm

concurrency:
  max: 20
  exceed-action: QUEUE
  enable: true
  preemption:
    enable: true
    events: [mr_id]

on:
  workflow_dispatch:
  pull_request_comment:
    types: [created]
    branches: [ '**' ]
    comments: [ '^(?:\/)?compile*' ]
  pr_comment:
    types: [ created ]
    keyword: '^(?:\/)?compile*'

env:
  org_name: ${{ vars.ORG_NAME }}
  repo_name: ${{ atomgit.event.repository.name }}
  MERGE_ID: ${{ atomgit.event.pull_request.number }}
  TARGET_BRANCH: ${{ atomgit.base_ref }}
  SOURCE_BRANCH: ${{ atomgit.head_ref }}
  obs_path: "${{ env.org_name }}/${{ env.repo_name }}/ci/package/${{ env.MERGE_ID }}"
  obs_smoke_path_A2: "${{ env.obs_path }}/presmoke/2" 
  obs_smoke_path_A3: "${{ env.obs_path }}/presmoke/3"
  online: ${{ vars.APPLY_LABEL }}

stages:
  stage1:
    name: PreBuild
    jobs:
      JOB_image:
        name: Test_image
        steps:
          - name: revise_image
            identifier: revise_image
            uses: cann/.gitcode/actions/revise-img@master
            with:
              repo_name: ${{ env.repo_name }}
              target_branch: ${{ env.TARGET_BRANCH }}
              repo_url: ${{ vars.CI_PATH }}
          -
            name: show_output
            run: |
              echo "image: ${{ steps.revise_image.outputs.Compile_Ascend_ARM }}"
        runs-on: ["self-hosted", "arch=x64", "spec=small"]
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/ubuntu20.04.05_x86:k8s_v1.1006
      JOB_pre:
        name: Test_PreBuild
        uses: cann/.gitcode/.gitcode/workflows/pre_action.yml@master
    pre:
    - type: auto
    fail-fast: true
  stage2:
    name: compile
    jobs:
      JOB_x86_compile:
        name: Compile_x86
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_X86'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_X86 }}
          arch: 'x64'
          package_name: 'cann-hcomm_linux-x86_64.run'
      JOB_x86_compile_ubuntu24:
        name: Compile_x86_ubuntu24
        if: env.TARGET_BRANCH == 'master'
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_X86_ubuntu24'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_X86_ubuntu24 }}
          arch: 'x64'
          package_name: 'cann-hcomm_linux-x86_64_ubuntu24.run'
      JOB_arm_compile:
        name: Compile_arm
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_ARM'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_ARM }}
          arch: 'arm64'
          package_name: 'cann-hcomm_linux-aarch64.run'
      JOB_arm_compile_ubuntu24:
        name: Compile_arm_ubuntu24
        if: env.TARGET_BRANCH == 'master'
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_ARM_ubuntu24'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_ARM_ubuntu24 }}
          arch: 'arm64'
          package_name: 'cann-hcomm_linux-aarch64_ubuntu24.run'
      JOB_codecheck:
        name: CodeCheck
        uses: cann/.gitcode/.gitcode/workflows/codecheck_action.yml@master
        with:
          precommit_image_version: ${{ jobs.JOB_image.outputs.precommit }}
          codecheck_image_version: ${{ jobs.JOB_image.outputs.codecheck }}
      JOB_staticcheck_md_check:
        name: CodeCheck_staticcheck_md_check
        uses: .gitcode/workflows/staticcheck_action.yml
        with:
          check_type: 'md_check'
          image_version: ${{ jobs.JOB_image.outputs.staticcheck }}
    pre:
    - type: auto
    fail-fast: false
  stage3:
    name: llt
    jobs:
      JOB_api_check:
        name: API_Check
        steps:
          -
            name: api-check
            identifier: api-check
            uses: cann/.gitcode/actions/api-check@master
            with:
              org_name: ${{ env.org_name }}
              mode: check
              repo_name: ${{ env.repo_name }}
              merge_id: ${{ env.MERGE_ID }}
        if: env.TARGET_BRANCH == 'master'
        runs-on: ["self-hosted", "arch=x64", "spec=small"]
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/${{ jobs.JOB_image.outputs.API_Check }}
      JOB_ut:
        name: UT_hcomm
        uses: .gitcode/workflows/ut_action.yml
        with:
          image_version: ${{ jobs.JOB_image.outputs.UT_Test }}
      JOB_st:
        name: ST_hcomm
        uses: .gitcode/workflows/st_action.yml
        with:
          image_version: ${{ jobs.JOB_image.outputs.UT_Test }}
    pre:
    - type: auto
    fail-fast: false
  stage4:
    name: PreSmoke
    jobs:
      A2_smoke:
        name: PreSmoke_A2
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              token: ${{secrets.GIT_TOKEN}}
              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
          -
            name: download
            uses: obs-download
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{ secrets.AK }}
              secret-key: ${{ secrets.SK }}
              key: |
                ${{ env.obs_path }}/pr_filelist.txt
                ${{ env.obs_path }}/pr_filelist_mod.txt
                ${{ env.obs_path }}/update_file_detail.txt
                ${{ env.obs_path }}/pre_smoke.sh
              path: ${{ steps.process_checkout.outputs.path }}
          -
            name: smoke executor
            timeout-minutes: 30
            run: |
              set -e
              export repo_name=${{env.repo_name}}
              export pr_id=${{ env.MERGE_ID }}
              export AK=${{secrets.AK}}
              export SK=${{secrets.SK}}
              export obs_smoke_path=${{ env.obs_smoke_path_A2 }}
              export obs_path=${{ env.obs_path }}
              export WORKSPACE=${{ steps.process_checkout.outputs.path }}
              bash ${{ steps.process_checkout.outputs.path }}/pre_smoke.sh
          - name: upload
            uses: obs-upload
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{ secrets.AK }}
              secret-key: ${{ secrets.SK }}
              artifact-path: "${{ steps.process_checkout.outputs.path }}/slog*.tar.gz"
              object-prefix: ${{ env.obs_smoke_path_A2 }}/plog/
        if: env.TARGET_BRANCH == 'master'
        runs-on: ['self-hosted','npu=4','smoke=204']
        container:
          image: swr.cn-south-1.myhuaweicloud.com/pre_smoke/${{ jobs.JOB_image.outputs.PreSmoke_A900_npupool }}
      A3_smoke:
        name: PreSmoke_A3
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              token: ${{secrets.GIT_TOKEN}}
              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
          -
            name: download
            uses: obs-download
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{ secrets.AK }}
              secret-key: ${{ secrets.SK }}
              key: |
                ${{ env.obs_path }}/pr_filelist.txt
                ${{ env.obs_path }}/pr_filelist_mod.txt
                ${{ env.obs_path }}/update_file_detail.txt
                ${{ env.obs_path }}/pre_smoke.sh
              path: ${{ steps.process_checkout.outputs.path }}
          -
            name: smoke executor
            timeout-minutes: 30
            run: |
              export obs_smoke_path=${{env.obs_smoke_path_A3}}
              export obs_path=${{ env.obs_path }}
              export repo_name=${{env.repo_name}}
              export pr_id=${{ env.MERGE_ID }}
              export AK=${{secrets.AK}}
              export SK=${{secrets.SK}}
              export WORKSPACE=${{ steps.process_checkout.outputs.path }}
              bash ${{ steps.process_checkout.outputs.path }}/pre_smoke.sh
          - name: upload
            uses: obs-upload
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{ secrets.AK }}
              secret-key: ${{ secrets.SK }}
              artifact-path: "${{ steps.process_checkout.outputs.path }}/slog*.tar.gz"
              object-prefix: ${{ env.obs_smoke_path_A3 }}/plog/
        if: env.TARGET_BRANCH == 'master'
        runs-on: ['self-hosted','npu=4','smoke=301']
        container:
          image: swr.cn-north-12.myhuaweicloud.com/pre_smoke/${{jobs.JOB_image.outputs.PreSmoke_A3_npupool}}
    pre:
    - type: auto
    fail-fast: false
    

post:
  jobs: 
    job_post:
      name: Test_post
      uses: cann/.gitcode/.gitcode/workflows/post_action.yml@master
