# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

[RunAicpuKfcResInitV2]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuKfcResInitV2

[RunAicpuRpcSrvLaunchV2]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_broadcast]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_allreduce]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_reduce]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_send]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_receive]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_allgather]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_reduce_scatter]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_alltoallv]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_alltoallvc]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_alltoall]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_gather]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_scatter]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_batch_send_recv]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_batch_put]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_batch_get]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_allgather_v]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_reduce_scatter_v]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_batch_write]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_half_alltoallv]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_finalize]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuRpcSrvLaunchV2_barrier]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunchV2

[RunAicpuKfcResInit]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuKfcResInit

[RunAicpuRpcSrvLaunch]
opInfo.opKernelLib=KFCKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuRpcSrvLaunch

[RunTransportRoceTx]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunTransportRoceTx

[RunTransportRoceRx]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunTransportRoceRx

[RunAicpuIndOpChannelInit]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuIndOpChannelInit

[RunAicpuIndOpChannelInitV2]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuIndOpChannelInitV2

[RunAicpuIndOpChannelUpdateV2]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuIndOpChannelUpdateV2

[RunAicpuIndOpNotify]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuIndOpNotify

[RunAicpuIndOpThreadInit]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuIndOpThreadInit

[RunAicpuCommInit]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuCommInit

[HcclKernelEntrance]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=HcclKernelEntrance

[HcclUpdateCommKernelEntrance]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=HcclUpdateCommKernelEntrance

[HcclDpuTaskexpShmemRestore]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=HcclDpuTaskexpShmemRestore

[RunAicpuThreadInit]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuThreadInit

[RunAicpuThreadDestroy]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuThreadDestroy

[RunAicpuThreadSupplementNotify]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuThreadSupplementNotify

[RunAicpuChannelInitV2]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuChannelInitV2

[RunAicpuChannelInitV3]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuChannelInitV3

[RunAicpuChannelDestroyV2]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuChannelDestroyV2
[RunAicpuKfcClearOpRes]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuKfcClearOpRes

[RunAicpuNotifyWaitAicpuKernel]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuNotifyWaitAicpuKernel

[RunAicpuNotifyRecordAicpuKernel]
opInfo.opKernelLib=CUSTAICPUKernel
opInfo.kernelSo=libaicpu_custom.so
opInfo.functionName=RunAicpuNotifyRecordAicpuKernel
